第3章の章末演習問題

### [1] list(range(9))からテンソルaを作成して、サイズ、オフセット、ストライドを確認してください。
※ ここではGoogle Colaraboratoryでの実行を想定しています。


#### （a） b = a.view(3, 3)を使って新しいテンソルを作成します。viewはどんな動作をするのか？またaとbが同じストレージを共有していることを確認してください。

In [2]:
# 回答
import torch

In [22]:
a = torch.tensor(list(range(9)))
print("size:",a.size())
print("offset",a.storage_offset())
print("stride",a.stride())

size: torch.Size([9])
offset 0
stride (1,)


In [14]:
b = a.view(3,3)

print(id(a.storage) == id(b.storage))


True


#### （b） テンソル c = b[1:,1:]を作成し、サイズ、オフセット、ストライドを確認してください

In [20]:
# 回答
c = b[1:,1:]
print("c:",c)
print("size:",c.size())
print("offset",c.storage_offset())
print("stride",c.stride())


c: tensor([[4, 5],
        [7, 8]])
size: torch.Size([2, 2])
offset 4
stride (3, 1)


### [2] torch ライブラリからcosineやsquare rootのような数学の演算に対応する関数を見つけてください。

#### （a） 関数を要素ごとに変数aに適用してください。なぜエラーが発生するのでしょう？

In [28]:
# 回答
print(a.dtype)
print(torch.cos(a))
print(torch.sqrt(a))


torch.int64
tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])


#### （b） 関数を実行可能にするために、どのような操作が必要なのでしょうか？

In [29]:
# 回答
print(torch.cos(a.float()))
print(torch.sqrt(a.float()))

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])
tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])


#### （c） 何か自作の関数があれば、動かしてみましょう。

In [ ]:
# 省略

以上。
