In [1]:
a = [1.0, 2.0, 3.0]

In [2]:
a[0]

1.0

In [4]:
a[2] = 4.0
a

[1.0, 2.0, 4.0]

In [5]:
import torch
a = torch.ones(3) #1が3つ格納されたテンソル
a

tensor([1., 1., 1.])

In [6]:
a[1]

tensor(1.)

In [7]:
float(a[1])

1.0

In [8]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [9]:
points = torch.zeros(6)
#zerosを使うのはただ要素数6のテンソルを作るため
points[0] = 4.0
points[1] = 1.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [10]:
points = torch.tensor([4.0, 1.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 3., 2., 1.])

In [11]:
float(points[0]),float(points[1])

(4.0, 1.0)

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [13]:
points.shape

torch.Size([3, 2])

In [16]:
points = torch.ones(3, 2)
points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [17]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points[0,1]

tensor(1.)

In [18]:
points[0]

tensor([4., 1.])