In [1]:
import torch

In [5]:
double_points = torch.ones(10, 2, dtype=torch.double)
print(double_points)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
print(short_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 2],
        [3, 4]], dtype=torch.int16)


In [6]:
short_points.dtype

torch.int16

In [9]:
double_points = torch.zeros(10,2).double()
print(double_points)
short_points = torch.ones(10,2).short()
print(short_points)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [10]:
double_points = torch.zeros(10,2).to(torch.double) 
print(double_points)
short_points = torch.ones(10,2).to(dtype=torch.short)
print(short_points)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)


In [17]:
points_64 = torch.rand(5, dtype=torch.double)
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0, 0, 0, 0, 0], dtype=torch.int16)

In [18]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [19]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [20]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

/var/folders/5x/f6ds179521j382hhjsp146x80000gn/T/ipykernel_5419/2923139482.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points.storage()
/Users/ishikawaritsuki/.pyenv/versions/3.10.6/lib/python3.10/site-packages/IPython/lib/pretty.py:778: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  output = repr(obj)
/Users/ishikawaritsuki/.pyenv/versions/3.10.6/lib/python3.10/site-packages/torch/storage.py:645: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only 

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [22]:
points_storage = points.storage()
print(points_storage[0])
print(points.storage()[1])

4.0
1.0


/var/folders/5x/f6ds179521j382hhjsp146x80000gn/T/ipykernel_5419/4231602901.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage = points.storage()
/var/folders/5x/f6ds179521j382hhjsp146x80000gn/T/ipykernel_5419/4231602901.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  print(points_storage[0])
/var/folders/5x/f6ds179521j382hhjsp146x80000gn/T/ipykernel_5419/4231602901.py:3: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class.

In [23]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

/var/folders/5x/f6ds179521j382hhjsp146x80000gn/T/ipykernel_5419/2616098612.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage = points.storage()
/var/folders/5x/f6ds179521j382hhjsp146x80000gn/T/ipykernel_5419/2616098612.py:3: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  points_storage[0] = 2.0


tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [26]:
a = torch.ones(3, 2)
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [27]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()

2

In [28]:
second_point.size()

torch.Size([2])

In [29]:
points.stride()

(2, 1)

In [30]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [31]:
second_point.storage_offset()

2

In [32]:
second_point.stride()

(1,)

In [37]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [42]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [43]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [44]:
id(points.storage()) == id(points_t.storage())

/var/folders/5x/f6ds179521j382hhjsp146x80000gn/T/ipykernel_5419/2282178668.py:1: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  id(points.storage()) == id(points_t.storage())


True

In [45]:
some_t = torch.ones(3,4,5)
transpose_t = some_t.transpose(0,2)
print(some_t.shape)
print(transpose_t.shape)

torch.Size([3, 4, 5])

In [48]:
print(some_t.stride())
print(transpose_t.stride())

(20, 5, 1)
(1, 5, 20)
